package com.gemini.live;

import android.accessibilityservice.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.view.accessibility.*;import java.util.*;

public class VolumeTriggerService extends AccessibilityService {
    public static VolumeTriggerService instance; final Handler h=new Handler(Looper.getMainLooper()); long lastDown;
    final ArrayList<Rect> bounds=new ArrayList<>(); final ArrayList<AccessibilityNodeInfo> nodes=new ArrayList<>();
    @Override public void onServiceConnected(){instance=this;super.onServiceConnected();}
    @Override public void onDestroy(){instance=null;clear();super.onDestroy();}
    @Override public void onInterrupt(){}
    @Override protected boolean onKeyEvent(KeyEvent e){if(e.getKeyCode()==KeyEvent.KEYCODE_VOLUME_DOWN&&e.getAction()==KeyEvent.ACTION_DOWN){long n=SystemClock.uptimeMillis();if(n-lastDown<450){lastDown=0;Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v!=null)v.vibrate(VibrationEffect.createOneShot(45,VibrationEffect.DEFAULT_AMPLITUDE));Intent i=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);startActivity(i);return true;}lastDown=n;}return super.onKeyEvent(e);}
    void clear(){for(AccessibilityNodeInfo n:nodes)if(n!=null)n.recycle();nodes.clear();bounds.clear();}
    @Override public void onAccessibilityEvent(AccessibilityEvent e){if(e==null)return;}
    AccessibilityNodeInfo root(){return getRootInActiveWindow();}
    public String read(){AccessibilityNodeInfo r=root();if(r==null)return "No active window.";clear();StringBuilder b=new StringBuilder("=== CANDIDATE INTERACTIVE ELEMENTS ===\n");walk(r,b,0);b.append("\n=== SCREEN TEXT ===\n");text(r,b,0);r.recycle();return b.toString();}
    void walk(AccessibilityNodeInfo n,StringBuilder b,int depth){if(n==null||depth>24||bounds.size()>=30)return;if(n.isClickable()||n.isEditable()||n.isFocusable()||n.isLongClickable()){Rect r=new Rect();n.getBoundsInScreen(r);if(r.width()>4&&r.height()>4){int id=bounds.size();bounds.add(new Rect(r));nodes.add(AccessibilityNodeInfo.obtain(n));CharSequence t=n.getText(),d=n.getContentDescription();String label=t!=null?t.toString().trim():d!=null?d.toString().trim():"Button";if(label.length()>80)label=label.substring(0,80);b.append("[#").append(id).append("] ").append(n.isEditable()?"Input ":"Button ").append('\"').append(label).append("\" at ").append(r.centerX()).append(',').append(r.centerY()).append('\n');}}
        for(int i=0;i<n.getChildCount();i++)walk(n.getChild(i),b,depth+1);
    }
    void text(AccessibilityNodeInfo n,StringBuilder b,int depth){if(n==null||depth>24)return;CharSequence t=n.getText();if(t!=null&&t.length()>0)b.append(t).append('\n');else{CharSequence d=n.getContentDescription();if(d!=null&&d.length()>0)b.append(d).append('\n');}for(int i=0;i<n.getChildCount();i++)text(n.getChild(i),b,depth+1);}
    public String tapId(int id){if(id<0||id>=bounds.size())return "Invalid element ID.\n"+read();Rect r=bounds.get(id);return tap(r.centerX(),r.centerY())?"Tapped element #"+id:"Tap failed";}
    public String longId(int id){if(id<0||id>=bounds.size())return "Invalid element ID.\n"+read();AccessibilityNodeInfo n=nodes.get(id);if(n!=null&&n.isLongClickable()&&n.performAction(AccessibilityNodeInfo.ACTION_LONG_CLICK))return "Long-pressed element #"+id;Rect r=bounds.get(id);return longPress(r.centerX(),r.centerY())?"Long-pressed element #"+id:"Long press failed";}
    public boolean tap(int x,int y){if(Build.VERSION.SDK_INT<24)return false;Path p=new Path();p.moveTo(x,y);p.lineTo(x+1,y+1);return dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,90)).build(),null,null);}
    public boolean longPress(int x,int y){if(Build.VERSION.SDK_INT<24)return false;Path p=new Path();p.moveTo(x,y);p.lineTo(x+1,y+1);return dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,750)).build(),null,null);}
    public boolean swipe(int a,int b,int c,int d,int ms){if(Build.VERSION.SDK_INT<24)return false;Path p=new Path();p.moveTo(a,b);p.lineTo(c,d);return dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,Math.max(100,ms))).build(),null,null);}
    public boolean scroll(String d){android.util.DisplayMetrics m=getResources().getDisplayMetrics();int x=m.widthPixels/2;return "up".equalsIgnoreCase(d)?swipe(x,(int)(m.heightPixels*.3),x,(int)(m.heightPixels*.8),300):swipe(x,(int)(m.heightPixels*.8),x,(int)(m.heightPixels*.3),300);}
    AccessibilityNodeInfo focused(AccessibilityNodeInfo n){if(n==null)return null;if(n.isFocused()||n==n.findFocus(AccessibilityNodeInfo.FOCUS_INPUT))return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo x=focused(n.getChild(i));if(x!=null)return x;}return null;}
    AccessibilityNodeInfo editable(AccessibilityNodeInfo n){if(n==null)return null;if(n.isEditable())return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo x=editable(n.getChild(i));if(x!=null)return x;}return null;}
    public String replace(String s){AccessibilityNodeInfo r=root();if(r==null)return "No active window.";AccessibilityNodeInfo n=r.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);if(n==null)n=editable(r);if(n==null){r.recycle();return "No editable field.";}Bundle b=new Bundle();b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,s);boolean ok=n.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);n.recycle();r.recycle();return ok?"Replaced text successfully.":"Could not replace text.";}
    public String type(String s){AccessibilityNodeInfo r=root();if(r==null)return "No active window.";AccessibilityNodeInfo n=r.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);if(n==null)n=editable(r);if(n==null){r.recycle();return "No editable field.";}ClipboardManager c=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("voice",s));boolean ok=n.performAction(AccessibilityNodeInfo.ACTION_PASTE);if(!ok){Bundle b=new Bundle();b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,s);ok=n.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);}n.recycle();r.recycle();return ok?"Inserted text.":"Could not insert text.";}
    public String tapLabel(String label){AccessibilityNodeInfo r=root();if(r==null)return "No active window.";AccessibilityNodeInfo n=find(r,label.toLowerCase());if(n==null){r.recycle();return "Element not found.";}Rect x=new Rect();n.getBoundsInScreen(x);n.recycle();r.recycle();return tap(x.centerX(),x.centerY())?"Tapped":"Tap failed";}
    AccessibilityNodeInfo find(AccessibilityNodeInfo n,String q){if(n==null)return null;CharSequence a=n.getText(),d=n.getContentDescription();if((a!=null&&a.toString().toLowerCase().contains(q))||(d!=null&&d.toString().toLowerCase().contains(q)))return AccessibilityNodeInfo.obtain(n);for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo x=find(n.getChild(i),q);if(x!=null)return x;}return null;}
    public String navigate(String a){int x;switch(a){case "back":x=GLOBAL_ACTION_BACK;break;case "recents":x=GLOBAL_ACTION_RECENTS;break;case "notifications":x=GLOBAL_ACTION_NOTIFICATIONS;break;case "quick_settings":x=GLOBAL_ACTION_QUICK_SETTINGS;break;case "lock":x=GLOBAL_ACTION_LOCK_SCREEN;break;default:x=GLOBAL_ACTION_HOME;}return performGlobalAction(x)?"Done":"Failed";}
}
